### ISSUE TITLE
webpack-dev-server fails to rebuild on watch

### ISSUE THREAD

**Issue by garth** [webpack/enhanced-resolve#102]
```
enhanced-resolve/lib/CachedInputFileSystem.js:145
			if(key.startsWith(what))
			      ^

TypeError: Cannot read property 'startsWith' of undefined
    at Storage.purge (enhanced-resolve/lib/CachedInputFileSystem.js:145:10)
    at Storage.purge (enhanced-resolve/lib/CachedInputFileSystem.js:150:9)
    at CachedInputFileSystem.purge (enhanced-resolve/lib/CachedInputFileSystem.js:259:20)
    at Watchpack.watcher.once (webpack/lib/node/NodeWatchFileSystem.js:42:26)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at Watchpack.emit (events.js:213:7)
    at Watchpack._onTimeout (watchpack/lib/watchpack.js:142:7)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

**Comment by lajosbencz** [comment]
Same here with these commands:
```
vue init webpack my-project
cd my-project
node build/dev-server.js
```

**Comment by bdfoster** [comment]
Problem is already fixed in v3.4.1.

**Comment by kulakowka** [comment]
I have some error, too...

**Comment by bdfoster** [comment]
Duplicate of #99

**Comment by garth** [comment]
Confirmed to be fixed
