### ISSUE TITLE
Bug: TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by robcresswell** [webpack/enhanced-resolve#104]
I've been seeing this a lot this morning (full trace):

```
/Users/robcresswell/icing/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:145
			if(key.startsWith(what))
			      ^

TypeError: Cannot read property 'startsWith' of undefined
    at Storage.purge (/Users/robcresswell/icing/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:145:10)
    at Storage.purge (/Users/robcresswell/icing/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:150:9)
    at CachedInputFileSystem.purge (/Users/robcresswell/icing/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:20)
    at Watchpack.watcher.once (/Users/robcresswell/icing/node_modules/webpack/lib/node/NodeWatchFileSystem.js:42:26)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at Watchpack.emit (events.js:213:7)
    at Watchpack._onTimeout (/Users/robcresswell/icing/node_modules/watchpack/lib/watchpack.js:142:7)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
```

It occurs any time a reload is prompted when using webpack-dev-server w/ hot-reload & Vue.

**Comment by robcresswell** [comment]
Ah, I apologise, it's a duplicate. Sorry for the time waste.
