### ISSUE TITLE
CachedInputFileSystem - TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by liujingbreak** [webpack/enhanced-resolve#106]
Environment: Webpack 3.2.0, 3.3.0.

When it is used with **babel-loader**, **webpack-dev-middleware** (watch mode is on), sometime when a JS file changed, webpack is triggered to re-compile:

```js
TypeError: Cannot read property 'startsWith' of undefined
    at Storage.purge (/Users/liujing/dianrong/dr-frontend/drcp-workspace/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:145:10)
    at Storage.purge (/Users/liujing/dianrong/dr-frontend/drcp-workspace/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:150:9)
    at CachedInputFileSystem.purge (/Users/liujing/dianrong/dr-frontend/drcp-workspace/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:20)
    at EventEmitter.watcher.once (/Users/liujing/dianrong/dr-frontend/drcp-workspace/node_modules/webpack/lib/node/NodeWatchFileSystem.js:42:26)
    at EventEmitter.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter._onTimeout (/Users/liujing/dianrong/dr-frontend/drcp-workspace/node_modules/watchpack/lib/watchpack.js:142:7)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5) TypeError: Cannot read property 'startsWith' of undefined
    at Storage.purge (/Users/liujing/dianrong/dr-frontend/drcp-workspace/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:145:10)
    at Storage.purge (/Users/liujing/dianrong/dr-frontend/drcp-workspace/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:150:9)
    at CachedInputFileSystem.purge (/Users/liujing/dianrong/dr-frontend/drcp-workspace/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:20)
    at EventEmitter.watcher.once (/Users/liujing/dianrong/dr-frontend/drcp-workspace/node_modules/webpack/lib/node/NodeWatchFileSystem.js:42:26)
    at EventEmitter.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter._onTimeout (/Users/liujing/dianrong/dr-frontend/drcp-workspace/node_modules/watchpack/lib/watchpack.js:142:7)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

I drilled down a little bit, found out, it was because **babel-loader** doing with `loaderOptions.babelrc`
```js
var babelrcPath = null;
if (loaderOptions.babelrc !== false) {
babelrcPath = exists(fileSystem, loaderOptions.babelrc) ? loaderOptions.babelrc : resolveRc(fileSystem, path.dirname(filename));
}
```

So if I don't set an option `babelrc` for babel-loader, it might cache a `undefined` file name to CachedInputFileSystem via `exist()`, which is the target that`.startsWith` calls to later on.

I don't know why  I can't reproduce in all Webpack projects, but I think calling `.startsWith` to a string without checking it with `!= null` is problematic.

**Comment by sokra** [comment]
fixed in 3.4.1
