### ISSUE TITLE
`lib/Resolve.js` has thrown an error under npm@5.1.0 and node@7.4.0

### ISSUE THREAD

**Issue by aleen42** [webpack/enhanced-resolve#111]
Recently I have upgraded node to version 7.4.0 and npm to 5.1.0 and failed to build my project with Webpack. In the gulp file, I have the following snippet:

```js
webpack(require('./build/webpack/config-prod'), function(err, stats) {
    if (err) throw new gutil.PluginError('webpack', err);
});
```

But when I run it, I failed to build with following error logged out:

```
[gulp] /home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/gulpfile.js:131
[gulp]         if (err) throw new gutil.PluginError('webpack', err);
[gulp]                  ^
[gulp] Error
[gulp]     at /home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/webpack/lib/Compilation.js:229:38
[gulp]     at onDoneResolving (/home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
[gulp]     at /home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/webpack/lib/NormalModuleFactory.js:85:20
[gulp]     at /home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/webpack/node_modules/async/lib/async.js:726:13
[gulp]     at /home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/webpack/node_modules/async/lib/async.js:52:16
[gulp]     at done (/home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/webpack/node_modules/async/lib/async.js:241:17)
[gulp]     at /home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/webpack/node_modules/async/lib/async.js:44:16
[gulp]     at /home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/webpack/node_modules/async/lib/async.js:723:17
[gulp]     at /home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/webpack/node_modules/async/lib/async.js:167:37
[gulp]     at /home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
[gulp]     at onResolved (/home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
[gulp]     at innerCallback (/home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/enhanced-resolve/lib/Resolver.js:88:19)
[gulp]     at loggingCallbackWrapper (/home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
[gulp]     at /home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/tapable/lib/Tapable.js:134:6
[gulp]     at loggingCallbackWrapper (/home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
[gulp]     at innerCallback (/home/gitlab-runner/builds/4fb49748/0/coremail/cmj/template.NG/node_modules/enhanced-resolve/lib/Resolver.js:94:11)
```

And my version of Webpack is 1.13.2

Is there any working around for solving the problem without upgrading Webpack?

**Comment by evilebottnawi** [comment]
Sorry for delay, node@7.4.0 is not supported anymore, if you still have a problem please open a new issue with reproducible test repo
