### ISSUE TITLE
cannot resolve es5-ext file paths that contain # as folder name

### ISSUE THREAD

**Issue by jklimke** [webpack/enhanced-resolve#282]
We experienced a broken Webpack build that is caused by the following line:

https://github.com/webpack/enhanced-resolve/blob/ff16fc2854f0960093142297af376c67777bb2f4/lib/Resolver.js#L282

The 'es5-ext' module is requiring a string extension that lives in a folder that is named '#'  [link to folder in project](https://github.com/medikoo/es5-ext/tree/master/string)

required path: ```./string/#/contains/index.js```

this is converted to ```./string/\0#/contains/index.js``` that cannot be resolved.

That leads to webpack crashing With the following error when followup plugins.

Webpack run stack strace (project root redacted)
```
internal/fs/utils.js:574
    throw err;
    ^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '/node_modules/es5-ext/string/\x00#/contains'
    at Object.readdir (fs.js:949:10)
    at go$readdir (/node_modules/graceful-fs/graceful-fs.js:202:23)
    at Object.readdir (/node_modules/graceful-fs/graceful-fs.js:184:12)
    at CacheBackend.provide (/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:193:18)
    at CaseSensitivePathsPlugin.getFilenamesInDir (/node_modules/case-sensitive-paths-webpack-plugin/index.js:58:6)
    at CaseSensitivePathsPlugin.fileExistsWithCase (/node_modules/case-sensitive-paths-webpack-plugin/index.js:89:8)
    at checkFile (/node_modules/case-sensitive-paths-webpack-plugin/index.js:147:10)
    at /node_modules/case-sensitive-paths-webpack-plugin/index.js:169:7
    at CaseSensitivePathsPlugin.primeCache (/node_modules/case-sensitive-paths-webpack-plugin/index.js:120:5)
    at onAfterResolve (/node_modules/case-sensitive-paths-webpack-plugin/index.js:164:10) {
  code: 'ERR_INVALID_ARG_VALUE'
}
```

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/12156? Can you provide small example?

**Comment by woodgear** [comment]
might that could be a good test case

**Comment by remorses** [comment]
I made a reproduction at https://github.com/remorses/enhanced-resolve-repro-hashtag

Tip: to check if a string contains the null (`\0`) character you can use `JOSN.stringify`, console.log won't show null characters

PS: I found this issue trying to resolve a package that uses https://gitpkg.vercel.app to be installed, using gitpkg.vercel.app you use # to specify the commit you want to install

**Comment by alexander-akait** [comment]
@denieler Can you provide reproducible test repo?

**Comment by vankop** [comment]
this probably caused by some plugin that gets "resolver" version of path ( with escaped symbols ), easy solution will be don't use `#` in path. 
_________

btw issue is solved in latest `webpack`/`enhanced-resolve`
