### ISSUE TITLE
`webpack` fails to resolve `@rollup/plugin-json`

### ISSUE THREAD

**Issue by x-yuri** [webpack/enhanced-resolve#319]
`package.json`:

```json
{
  "dependencies": {
    "@rollup/plugin-json": "^4.1.0",
    "webpack-cli": "^4.9.1"
  }
}
```

`src/index.js`:

```js
const json = require('@rollup/plugin-json');
json();
```

`webpack.config.js`:

```js
module.exports = {
    mode: 'development',
    target: 'node',
    resolve: {
        alias: {
            // '@rollup/plugin-json': '/tmp/tmp.SJEDmixLD7/node_modules/@rollup/plugin-json/dist/index.js',
        },
    },
    devtool: false,
};
```

```
$ npx webpack
asset main.js 73.9 KiB [emitted] (name: main)
runtime modules 670 bytes 3 modules
modules by path ./node_modules/ 66.6 KiB
  modules by path ./node_modules/picomatch/ 51.5 KiB
    ./node_modules/picomatch/index.js 60 bytes [built] [code generated]
    ./node_modules/picomatch/lib/picomatch.js 9.72 KiB [built] [code generated]
    ./node_modules/picomatch/lib/scan.js 8.97 KiB [built] [code generated]
    ./node_modules/picomatch/lib/utils.js 1.84 KiB [built] [code generated]
    ./node_modules/picomatch/lib/constants.js 4.34 KiB [built] [code generated]
    ./node_modules/picomatch/lib/parse.js 26.6 KiB [built] [code generated]
  modules by path ./node_modules/@rollup/ 15.1 KiB
    ./node_modules/@rollup/plugin-json/dist/index.es.js 1.05 KiB [built] [code generated]
    ./node_modules/@rollup/pluginutils/dist/es/index.js 14 KiB [built] [code generated]
./src/index.js 53 bytes [built] [code generated]
external "path" 42 bytes [built] [code generated]
webpack 5.64.2 compiled successfully in 220 ms

$ node dist/main.js
/tmp/tmp.SJEDmixLD7/dist/main.js:2720
json();
^

TypeError: json is not a function
    at /tmp/tmp.SJEDmixLD7/dist/main.js:2720:1
    at /tmp/tmp.SJEDmixLD7/dist/main.js:2722:3
    at Object.<anonymous> (/tmp/tmp.SJEDmixLD7/dist/main.js:2724:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

`dist/main.js`:

```js
/******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({

/***/ "./node_modules/@rollup/plugin-json/dist/index.es.js":
/*!***********************************************************!*\
  !*** ./node_modules/@rollup/plugin-json/dist/index.es.js ***!
  \***********************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
/* harmony import */ var _rollup_pluginutils__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @rollup/pluginutils */ "./node_modules/@rollup/pluginutils/dist/es/index.js");


function json(options) { ... }

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (json);
//# sourceMappingURL=index.es.js.map


/***/ }),

...

/******/ 	});

...

// This entry need to be wrapped in an IIFE because it need to be isolated against other modules in the chunk.
(() => {
/*!**********************!*\
  !*** ./src/index.js ***!
  \**********************/
const json = __webpack_require__(/*! @rollup/plugin-json */ "./node_modules/@rollup/plugin-json/dist/index.es.js");
json();

})();

/******/ })()
;
```

* `src/index.js` expects `require(...)` to return the `json()` function, but it returns `{default: function json() {...}}`
* the resolver is created with [`{dependencyType: 'esm'}`][a], because the [entrypoint][b] has category [`esm`][c]
* for [`esm`][d] `resolveOptions.mainFields` is [`['module', 'main']`][e], as such `module` is tried before `main`
* `@rollup/plugin-json` [has][f] [both][g], but the [`module` one][h] is an es module
* the same goes for `@rollup/plugin-replace`, `@rollup/plugin-commonjs`, and probably others
* the workaround is to alias the module

[a]: https://github.com/webpack/webpack/blob/v5.64.2/lib/NormalModuleFactory.js#L650-L659
[b]: https://github.com/webpack/webpack/blob/v5.64.2/lib/dependencies/EntryDependency.js#L24
[c]: https://github.com/webpack/webpack/blob/v5.64.2/lib/NormalModuleFactory.js#L748-L749
[d]: https://github.com/webpack/webpack/blob/v5.64.2/lib/WebpackOptionsApply.js#L633
[e]: https://github.com/webpack/webpack/blob/v5.64.2/lib/config/defaults.js#L1154
[f]: https://github.com/rollup/plugins/blob/json-v4.1.0/packages/json/package.json#L65
[g]: https://github.com/rollup/plugins/blob/json-v4.1.0/packages/json/package.json#L13
[h]: https://unpkg.com/browse/@rollup/plugin-json@4.1.0/dist/index.es.js

**Comment by alexander-akait** [comment]
Sorry, not related to webpack

**Comment by x-yuri** [comment]
Which means... a `rollup` bug? Or `module` is a non-standard field and everybody treats it as they see fit? And as such the responsibility to resolve such conflicts are on `webpack` users? Which is probably okay.

**Comment by sokra** [comment]
It resolves it fine. It exports an ESM which can be used like that:

``` js
const json = require('@rollup/plugin-json').default;
json();
```

or better:

``` js
import json from '@rollup/plugin-json';
json();
```
