### ISSUE TITLE
Cannot read property 'lastIndexOf' of undefined

### ISSUE THREAD

**Issue by rexxars** [webpack/enhanced-resolve#83]
Sorry for the crappy title, hard to figure out something descriptive for this.

I'm trying to create a webpack resolver/plugin where something arbitrary (`foo:bar:baz`) is resolved to a filesystem location (after some async work figuring out which file).

This is kind of hard, as I can't seem to hook in to the resolve infrastructure "early enough". I've added a regular resolver plugin, but the `apply()` method isn't called before webpack fails with an error that it can't resolve the module I'm trying to find.

In webpack 1, I made this work by adding a plugin that set up a hook on `compiler.resolvers.normal.plugin('module', () => {})`, resolved the request asyncronously and called `this.doResolve()` with a new request, pointing to a concrete file.

In webpack 2, I managed to do mostly the same (I have to wait for the `compilation` event being emitted before the resolvers are initialized), but when I pass the modified request to the  `doResolve()` method, it ends up crashing inside of enhanced-resolve (`TypeError: Cannot read property 'lastIndexOf' of undefined`). It looks like it's trying to find a `package.json` file. Not sure why this is needed, or how I can tell it to search a specific location for the file.

Any ideas? Suggestions? Are there any guides on how to make a totally custom resolver?

Stack trace:

```
/home/espenh/webdev/san/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFileUtils.js:84
  var i = directory.lastIndexOf("/"),
                   ^

TypeError: Cannot read property 'lastIndexOf' of undefined
    at cdUp (/home/espenh/webdev/san/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFileUtils.js:84:19)
    at /home/espenh/webdev/san/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFileUtils.js:50:17
    at /home/espenh/webdev/san/node_modules/webpack/node_modules/enhanced-resolve/lib/forEachBail.js:29:14
    at Array.<anonymous> (/home/espenh/webdev/san/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFileUtils.js:14:50)
    at Storage.finished (/home/espenh/webdev/san/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at /home/espenh/webdev/san/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
    at Array.<anonymous> (/home/espenh/webdev/san/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:182:20)
    at Storage.finished (/home/espenh/webdev/san/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at ReadFileContext.<anonymous> (/home/espenh/webdev/san/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9)
    at ReadFileContext.callback (/home/espenh/webdev/san/node_modules/graceful-fs/graceful-fs.js:78:16)
```

**Comment by jhnns** [comment]
Thanks for reporting this. Do you have any example repo you can share with us to reproduce this?

**Comment by rexxars** [comment]
Got some help from @bebraw today and eventually figured out that I was calling `doResolve()` without a `path` property in the second argument object. My bad, sorry.

**Comment by bebraw** [comment]
@jhnns Maybe [doResolve](https://github.com/webpack/enhanced-resolve/blob/739339de492e5d10023b48e6e8cf0edcedc5f6b5/lib/Resolver.js#L30) should force those parameters to be defined? Easier to catch issues like this. 👍
