### ISSUE TITLE
package.json with utf-8 bom fails

### ISSUE THREAD

**Issue by dherges** [webpack/enhanced-resolve#87]
Steps to reproduce:
1. npm and yarn install packages
2. the installed package has a `package.json` with utf-8 and bom (byte order marker)
3. webpack build fails with the following error

```
Module build failed: ModuleNotFoundError: Module not found: SyntaxError: <project>\node_modules\@nice\nice-fluorine-icons\pack
age.json (directory description file): SyntaxError: <project>\node_modules\@nice\nice-fluorine-icons\package.json (directory d
escription file): SyntaxError: Unexpected token ﻿ in JSON at position 0
    at factoryCallback (<project>\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:260:39)
    at factory (<project>\node_modules\@angular\cli\node_modules\webpack\lib\NormalModuleFactory.js:247:20)
    at resolver (<project>\node_modules\@angular\cli\node_modules\webpack\lib\NormalModuleFactory.js:65:21)
    at asyncLib.parallel.e (<project>\node_modules\@angular\cli\node_modules\webpack\lib\NormalModuleFactory.js:138:21)
    at <project>\node_modules\async\dist\async.js:3838:9
    at <project>\node_modules\async\dist\async.js:421:16
    at iteratorCallback (<project>\node_modules\async\dist\async.js:996:13)
    at <project>\node_modules\async\dist\async.js:906:16
    at <project>\node_modules\async\dist\async.js:3835:13
    at resolvers.normal.resolve (<project>\node_modules\@angular\cli\node_modules\webpack\lib\NormalModuleFactory.js:130:23)
    at onResolved (<project>\node_modules\enhanced-resolve\lib\Resolver.js:64:18)
    at loggingCallbackWrapper (<project>\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at innerCallback (<project>\node_modules\enhanced-resolve\lib\Resolver.js:121:19)
    at loggingCallbackWrapper (<project>\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at <project>\node_modules\tapable\lib\Tapable.js:283:15
    at <project>\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:36:19
```

Background:
we found a lenghty discussion on the npm repo. finally, npm [implemented utf-8 bom handling since npm 3.x](https://github.com/npm/npm/issues/3358#issuecomment-117678853)

Shouldn't it be implemented in webpack then, too?

**Comment by mikesherov** [comment]
@dherges thanks for contributing. I'll gladly accept a PR here, otherwise we'll eventually get around to it.
