### ISSUE TITLE
Failed to rebuild with webpack@2.4.5,throw exceptions that enhanced-resolve/lib/CachedInputFileSystem.js:145  if(key.startsWith(what))

### ISSUE THREAD

**Issue by qiudong** [webpack/enhanced-resolve#99]
```
/home/qd/project_1/fin-front/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:145
                        if(key.startsWith(what))
                              ^

TypeError: Cannot read property 'startsWith' of undefined
    at Storage.purge (/home/qd/project_1/fin-front/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:145:10)
    at Storage.purge (/home/qd/project_1/fin-front/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:150:9)
    at CachedInputFileSystem.purge (/home/qd/project_1/fin-front/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:20)
    at EventEmitter.<anonymous> (/home/qd/project_1/fin-front/node_modules/webpack/lib/node/NodeWatchFileSystem.js:42:26)
    at EventEmitter.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter._onTimeout (/home/qd/project_1/fin-front/node_modules/watchpack/lib/watchpack.js:142:7)
    at Timer.listOnTimeout (timers.js:92:15)

```
I start up is ok but I edit the file failed,I use ubuntu 16.10

**Comment by diegoprd** [comment]
Same with webpack 3.3.0 here.

**Comment by Fox32** [comment]
There is already #97

**Comment by lcxfs1991** [comment]
same with 3.3.0

**Comment by boonier** [comment]
Yep, same happening here

**Comment by lcxfs1991** [comment]
Please fix this ASAP because webpack use enhanced-resolve: "^3.3.0". I will upgrade to 3.4.0 if we install webpack fresh. Wondering whether this is a bug or a breaking change?

**Comment by lcxfs1991** [comment]
You can manually delete enahnced-resolve in node_modules and install version 3.3.0. It will fix temporarily.

**Comment by sokra** [comment]
3.4.1 should fix the problem

**Comment by awesomenaz** [comment]
@sokra  yeah just tested it out, this fixes the problem. Thank you, sir.

**Comment by the-architect** [comment]
Thank you @sokra ! Works! :)
